### ISSUE TITLE
Is Result still necessary for Scala 2.12?

### ISSUE THREAD

**Issue by janstenpickle** [albertpastrana/uscala#6]
Scala 2.12 has made `Either` right biased, in response the [cats library has deprecated `Xor`](https://github.com/typelevel/cats/issues/1192) and created implicit syntax for backwards compatibility with 2.11.

I'm not sure doing the same is really a good idea, as I'm not a big fan of implicit classes, however I do agree with their motivations for deprecating `Xor`. What do you think @albertpastrana?

**Comment by nathankleyn** [comment]
We've kept it for now because it's nice to have human naming for many of the things that otherwise don't read well with `Either` (eg. `Left` and `Right` vs `Fail` and `Ok`).

Also, the interoperability with `Either` is so good now that you can convert on your program boundary if you desire, both ways as you need.
